# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='0', max_length=128),
            preserve_default=False,
        ),
    ]
